# Generated by Django 6.0.1 on 2026-02-10 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OHEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_number", models.IntegerField()),
                (
                    "institution",
                    models.CharField(
                        choices=[
                            ("Animas Museum", "Animasmuseum"),
                            ("Center of Southwest Studies", "Centerofswstudies"),
                            ("Colorado State University", "Coloradostateuniversity"),
                            ("Denver Public Library", "Denverpubliclibrary"),
                            ("Dolores Public Library", "Dolorespubliclibrary"),
                            ("Durango Native Stories", "Durangonativestories"),
                            ("Durango Public Library", "Durangopubliclibrary"),
                            (
                                "Hinsdale County Historical Society",
                                "Hinsdalecountyhistoricalsociety",
                            ),
                            ("History Colorado", "Historycolorado"),
                            ("Ignacio Library", "Ignaciolibrary"),
                            ("KVNF", "Kvnf"),
                            ("Pine River Public Library", "Pineriverpubliclibrary"),
                            ("Ridgway Public Library", "Ridgwaypubliclibrary"),
                            (
                                "San Juan County Historical Society",
                                "Sanjuancountyhistoricalsociety",
                            ),
                            (
                                "Telluride Historical Museum",
                                "Telluridehistoricalmuseum",
                            ),
                            ("Wilkinson Public Library", "Wilkinsonpubliclibrary"),
                            (
                                "Ouray County Ranch History Museum",
                                "Ouraycountyranchhistorymuseum",
                            ),
                            ("Fort Lewis Mesa Library", "Fortlewismesalibrary"),
                        ],
                        max_length=100,
                    ),
                ),
                ("medium", models.CharField(max_length=100)),
                ("access", models.CharField(max_length=100)),
                ("year", models.IntegerField(blank=True, null=True)),
                ("month", models.IntegerField(blank=True, null=True)),
                ("day", models.IntegerField(blank=True, null=True)),
                ("narrator", models.CharField(blank=True, max_length=100, null=True)),
                ("creator", models.CharField(blank=True, max_length=100, null=True)),
                ("location", models.CharField(blank=True, max_length=1000, null=True)),
                ("topic", models.CharField(blank=True, max_length=1000, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                ("link", models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
