# Generated by Django 6.0.1 on 2026-02-16 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0002_remove_ohentry_item_number_alter_ohentry_institution"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ohentry",
            name="month",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
