# Generated by Django 6.0.1 on 2026-02-16 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0003_alter_ohentry_month"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ohentry",
            name="description",
            field=models.CharField(blank=True, max_length=1000000, null=True),
        ),
    ]
