# Generated by Django 6.0.1 on 2026-03-05 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0005_alter_ohentry_institution"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ohentry",
            name="institution",
            field=models.CharField(
                choices=[
                    ("Animas Museum", "Animas Museum"),
                    ("Center of Southwest Studies", "Center of Southwest Studies"),
                    ("Colorado State University", "Colorado State University"),
                    ("Denver Public Library", "Denver Public Library"),
                    ("Dolores Public Library", "Dolores Public Library"),
                    ("Durango Native Stories", "Durango Native Stories"),
                    ("Durango Public Library", "Durango Public Library"),
                    ("Fort Lewis Mesa Library", "Fort Lewis Mesa Library"),
                    (
                        "Hinsdale County Historical Society",
                        "Hinsdale County Historical Society",
                    ),
                    ("History Colorado", "History Colorado"),
                    ("Ignacio Library", "Ignacio Library"),
                    ("KVNF", "KVNF"),
                    ("Mancos Public Library", "Mancos Public Library"),
                    ("Montezuma Heritage Museum", "Montezuma Heritage Museum"),
                    (
                        "Ouray County Ranch History Museum",
                        "Ouray County Ranch History Museum",
                    ),
                    ("Pine River Public Library", "Pine River Public Library"),
                    ("Ridgway Public Library", "Ridgway Public Library"),
                    (
                        "San Juan County Historical Society",
                        "San Juan County Historical Society",
                    ),
                    ("Telluride Historical Museum", "Telluride Historical Museum"),
                    ("Wilkinson Public Library", "Wilkinson Public Library"),
                ],
                max_length=100,
            ),
        ),
    ]
