# Generated by Django 6.0.1 on 2026-03-17 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0006_alter_ohentry_institution"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ohentry",
            name="institution",
            field=models.CharField(max_length=100),
        ),
    ]
