# Generated by Django 6.0.1 on 2026-04-12 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0007_alter_ohentry_institution"),
    ]

    operations = [
        migrations.AddField(
            model_name="ohentry",
            name="date_updated",
            field=models.CharField(default="April 12, 2026", max_length=100),
        ),
    ]
