# Generated by Django 6.0.1 on 2026-04-12 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0008_ohentry_date_updated"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ohentry",
            name="date_updated",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="ohentry",
            name="narrator",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
